# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp sourceCpp
#' @useDynLib esback
#' @keywords internal
stationary_bootstrap_indices <- function(n, avg_block_size, B) {
    .Call('_esback_stationary_bootstrap_indices', PACKAGE = 'esback', n, avg_block_size, B)
}

